# Docker
- task: aquasecScanner@4
  inputs:
    image: 'accusoft/prizmdoc-editor:latest'
    scanType: 'dockerarchive'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    registry: 'accusoft/prizmdoc-editor:latest'
    connection: 'aqua-eks-morgan'
    caCertificates: true
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - master

# resources:
# - repo: self

# variables:
#   tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#           $(tag)
